export default function Head() {
  return (
    <>
      <title>Connect with Friends and Family on - P3Social</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="description" content="Stay connected with your friends and family using our social media app. Share photos, videos, and messages with ease." />
      <meta name="keywords" content="social media, app, friends, family, photos, messages" />
      <meta name="robots" content="index, follow" />
      <meta name="revisit-after" content="7 days" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
